//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterViewModel_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewModel_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.RegisterViewModel.uk", typeof(RegisterViewModel_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword поле є обов&apos;язковим.
        /// </summary>
        internal static string ConfirmPassword_поле_є_обов_язковим {
            get {
                return ResourceManager.GetString("ConfirmPassword поле є обов\'язковим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email поле є обов&apos;язвовим.
        /// </summary>
        internal static string Email_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("Email поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password поле є обов&apos;язвовим.
        /// </summary>
        internal static string Password_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("Password поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedRole поле є обов&apos;язвовим.
        /// </summary>
        internal static string SelectedRole_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("SelectedRole поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username поле є обов&apos;язвовим.
        /// </summary>
        internal static string Username_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("Username поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина Username має бути від 6 до 20 символів.
        /// </summary>
        internal static string Довжина_Username_має_бути_від_6_до_20_символів {
            get {
                return ResourceManager.GetString("Довжина Username має бути від 6 до 20 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінімальна довжина пароля - 6 символів.
        /// </summary>
        internal static string Мінімальна_довжина_пароля___6_символів {
            get {
                return ResourceManager.GetString("Мінімальна довжина пароля - 6 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не співпадають.
        /// </summary>
        internal static string Паролі_не_співпадають {
            get {
                return ResourceManager.GetString("Паролі не співпадають", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль має містити принаймні одну цифру, одну велику літеру та одну маленьку літеру.
        /// </summary>
        internal static string Пароль_має_містити_принаймні_одну_цифру__одну_велику_літеру_та_одну_маленьку_літеру {
            get {
                return ResourceManager.GetString("Пароль має містити принаймні одну цифру, одну велику літеру та одну маленьку літе" +
                        "ру", resourceCulture);
            }
        }
    }
}
