//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Views.Vacancy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VacancyDetails_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VacancyDetails_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Views.Vacancy.VacancyDetails.en", typeof(VacancyDetails_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About company.
        /// </summary>
        internal static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates from all over the world.
        /// </summary>
        internal static string AllWorld {
            get {
                return ResourceManager.GetString("AllWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vacancy was published on.
        /// </summary>
        internal static string CompanyPublished {
            get {
                return ResourceManager.GetString("CompanyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company website.
        /// </summary>
        internal static string CompanySite {
            get {
                return ResourceManager.GetString("CompanySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only candidates from Europe.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No experience.
        /// </summary>
        internal static string NoExperience {
            get {
                return ResourceManager.GetString("NoExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        internal static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy details.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only candidates from Ukraine.
        /// </summary>
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only candidates from Ukraine and Europe.
        /// </summary>
        internal static string UkraineEurope {
            get {
                return ResourceManager.GetString("UkraineEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        internal static string VacancyView {
            get {
                return ResourceManager.GetString("VacancyView", resourceCulture);
            }
        }
    }
}
