//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FavouriteListService_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FavouriteListService_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.Services.Resources.FavouriteListService.en", typeof(FavouriteListService_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vacancy has been successfully added to the list.
        /// </summary>
        internal static string AddedToListSuccess {
            get {
                return ResourceManager.GetString("AddedToListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate is on the list.
        /// </summary>
        internal static string CandidateInList {
            get {
                return ResourceManager.GetString("CandidateInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate has been successfully added to the list.
        /// </summary>
        internal static string CandidateSuccessAddToList {
            get {
                return ResourceManager.GetString("CandidateSuccessAddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate has been successfully removed from the list.
        /// </summary>
        internal static string CandidateSuccessRemoveFromList {
            get {
                return ResourceManager.GetString("CandidateSuccessRemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving a job or user.
        /// </summary>
        internal static string ErrorCandidateInList {
            get {
                return ResourceManager.GetString("ErrorCandidateInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user.
        /// </summary>
        internal static string ErrorGettingUser {
            get {
                return ResourceManager.GetString("ErrorGettingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user or the user is not a candidate.
        /// </summary>
        internal static string ErrorGettingUserOrUserNotCandidate {
            get {
                return ResourceManager.GetString("ErrorGettingUserOrUserNotCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user or the user is not a employer.
        /// </summary>
        internal static string ErrorGettingUserOrUserNotEmployer {
            get {
                return ResourceManager.GetString("ErrorGettingUserOrUserNotEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when receiving a vacancy.
        /// </summary>
        internal static string ErrorGettingVacancy {
            get {
                return ResourceManager.GetString("ErrorGettingVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving a vacancy or user.
        /// </summary>
        internal static string ErrorGettingVacancyOrUser {
            get {
                return ResourceManager.GetString("ErrorGettingVacancyOrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user.
        /// </summary>
        internal static string GettingUserError {
            get {
                return ResourceManager.GetString("GettingUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no candidate in the list.
        /// </summary>
        internal static string NoCandidateInList {
            get {
                return ResourceManager.GetString("NoCandidateInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no vacancy in the list.
        /// </summary>
        internal static string NoVacancyInList {
            get {
                return ResourceManager.GetString("NoVacancyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vacancy has been successfully removed from the list.
        /// </summary>
        internal static string RemoveFromListSuccess {
            get {
                return ResourceManager.GetString("RemoveFromListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user or the user is not a candidate.
        /// </summary>
        internal static string UserNotCandidate {
            get {
                return ResourceManager.GetString("UserNotCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vacancy is on the list.
        /// </summary>
        internal static string VacancyInList {
            get {
                return ResourceManager.GetString("VacancyInList", resourceCulture);
            }
        }
    }
}
