//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VacancyService_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VacancyService_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.Services.Resources.VacancyService.uk", typeof(VacancyService_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансія успішно додана до списку.
        /// </summary>
        internal static string AddedToListSuccess {
            get {
                return ResourceManager.GetString("AddedToListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час отримання вакансії сталася помилка.
        /// </summary>
        internal static string ErrorGettingVacancy {
            get {
                return ResourceManager.GetString("ErrorGettingVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час отримання вакансії або користувача сталася помилка.
        /// </summary>
        internal static string ErrorGettingVacancyOrUser {
            get {
                return ResourceManager.GetString("ErrorGettingVacancyOrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка отримання користувача.
        /// </summary>
        internal static string GettingUserError {
            get {
                return ResourceManager.GetString("GettingUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансії в списку немає.
        /// </summary>
        internal static string NoVacancyInList {
            get {
                return ResourceManager.GetString("NoVacancyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансія успішно видалена зі списку.
        /// </summary>
        internal static string RemoveFromListSuccess {
            get {
                return ResourceManager.GetString("RemoveFromListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка отримання користувача або користувач не є кандидатом.
        /// </summary>
        internal static string UserNotCandidate {
            get {
                return ResourceManager.GetString("UserNotCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансія є в списку.
        /// </summary>
        internal static string VacancyInList {
            get {
                return ResourceManager.GetString("VacancyInList", resourceCulture);
            }
        }
    }
}
