//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RespondedController_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RespondedController_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Controllers.RespondedController.uk", typeof(RespondedController_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При спробі відмінити відгук на вакансію відбулася помилка.
        /// </summary>
        internal static string ErrorWhenTryCancelRespondToVacancy {
            get {
                return ResourceManager.GetString("ErrorWhenTryCancelRespondToVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При спробі відгукнутися на вакансію виникла помилка.
        /// </summary>
        internal static string ErrorWhenTryRespondToVacancy {
            get {
                return ResourceManager.GetString("ErrorWhenTryRespondToVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви успішно відмінили відгук на вакансію.
        /// </summary>
        internal static string SuccessCancelRespondToVacancy {
            get {
                return ResourceManager.GetString("SuccessCancelRespondToVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви успішно відгукнулися на вакансію.
        /// </summary>
        internal static string SuccessRespondToVacancy {
            get {
                return ResourceManager.GetString("SuccessRespondToVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансій за вашим запитом не знайдено або з вакансіями не було проведено жодних дій.
        /// </summary>
        internal static string VacanciesNotFound {
            get {
                return ResourceManager.GetString("VacanciesNotFound", resourceCulture);
            }
        }
    }
}
