//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VacancyController_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VacancyController_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Controllers.VacancyController.uk", typeof(VacancyController_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при спробі створити вакансію.
        /// </summary>
        internal static string CreateVacancyError {
            get {
                return ResourceManager.GetString("CreateVacancyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансія успішно створена.
        /// </summary>
        internal static string CreateVacancySuccess {
            get {
                return ResourceManager.GetString("CreateVacancySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при спробі редагувати вакансію.
        /// </summary>
        internal static string EditVacancyError {
            get {
                return ResourceManager.GetString("EditVacancyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансію успішно обновлено.
        /// </summary>
        internal static string EditVacancySuccess {
            get {
                return ResourceManager.GetString("EditVacancySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не є власником вакансії.
        /// </summary>
        internal static string NotOwnerError {
            get {
                return ResourceManager.GetString("NotOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при спробі видалення вакансії.
        /// </summary>
        internal static string RemoveVacancyError {
            get {
                return ResourceManager.GetString("RemoveVacancyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансія успішно видалена.
        /// </summary>
        internal static string RemoveVacancySuccess {
            get {
                return ResourceManager.GetString("RemoveVacancySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансій за запитом не знайдено.
        /// </summary>
        internal static string VacanciesNotFoundError {
            get {
                return ResourceManager.GetString("VacanciesNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансію не знайдено або виникла помилка.
        /// </summary>
        internal static string VacancyNotFoundError {
            get {
                return ResourceManager.GetString("VacancyNotFoundError", resourceCulture);
            }
        }
    }
}
