//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _MainHeader_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MainHeader_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Views.Shared._MainHeader.uk", typeof(_MainHeader_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидати.
        /// </summary>
        internal static string HeaderAllCandidates {
            get {
                return ResourceManager.GetString("HeaderAllCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        internal static string HeaderChangePassword {
            get {
                return ResourceManager.GetString("HeaderChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        internal static string HeaderLogout {
            get {
                return ResourceManager.GetString("HeaderLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string HeaderMain {
            get {
                return ResourceManager.GetString("HeaderMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої вакансії.
        /// </summary>
        internal static string HeaderMyVacancies {
            get {
                return ResourceManager.GetString("HeaderMyVacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профайл.
        /// </summary>
        internal static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збережені.
        /// </summary>
        internal static string HeaderSaved {
            get {
                return ResourceManager.GetString("HeaderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансії.
        /// </summary>
        internal static string HeaderVacancies {
            get {
                return ResourceManager.GetString("HeaderVacancies", resourceCulture);
            }
        }
    }
}
