//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the site.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user fills out a profile, indicating his position, expected salary, level of English, describes his experience, and chooses a category..
        /// </summary>
        internal static string AboutSectionOne {
            get {
                return ResourceManager.GetString("AboutSectionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company offers various vacancies that the user can respond to, and you may be contacted..
        /// </summary>
        internal static string AboutSectionTwo {
            get {
                return ResourceManager.GetString("AboutSectionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everyone who works in IT..
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ButtonToRegister {
            get {
                return ResourceManager.GetString("ButtonToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UX/UI designers..
        /// </summary>
        internal static string Designers {
            get {
                return ResourceManager.GetString("Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevOps..
        /// </summary>
        internal static string DevOps {
            get {
                return ResourceManager.GetString("DevOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string ForCategories {
            get {
                return ResourceManager.GetString("ForCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string FormSend {
            get {
                return ResourceManager.GetString("FormSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM..
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to programmers.
        /// </summary>
        internal static string Programmers {
            get {
                return ResourceManager.GetString("Programmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testers..
        /// </summary>
        internal static string Testers {
            get {
                return ResourceManager.GetString("Testers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Ukraine.
        /// </summary>
        internal static string TitleEnd {
            get {
                return ResourceManager.GetString("TitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job.
        /// </summary>
        internal static string TitleMiddle {
            get {
                return ResourceManager.GetString("TitleMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site for search.
        /// </summary>
        internal static string TitleStart {
            get {
                return ResourceManager.GetString("TitleStart", resourceCulture);
            }
        }
    }
}
