//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.Views.Home.Index.uk", typeof(Index_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про сайт.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач заповнює профайл, вказуючи свою посаду, очікувану зарплату, рівень англійської, описує досвід, обирає категорію..
        /// </summary>
        internal static string AboutSectionOne {
            get {
                return ResourceManager.GetString("AboutSectionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компанія пропонує різні вакансії, на які користувач може відреагувати, і можливо, з вами зв&apos;яжуться..
        /// </summary>
        internal static string AboutSectionTwo {
            get {
                return ResourceManager.GetString("AboutSectionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вcix, хто працює в IT..
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шукати.
        /// </summary>
        internal static string ButtonToRegister {
            get {
                return ResourceManager.GetString("ButtonToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язатися з нами.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UX/UI дизайнерів..
        /// </summary>
        internal static string Designers {
            get {
                return ResourceManager.GetString("Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevOps..
        /// </summary>
        internal static string DevOps {
            get {
                return ResourceManager.GetString("DevOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для.
        /// </summary>
        internal static string ForCategories {
            get {
                return ResourceManager.GetString("ForCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити.
        /// </summary>
        internal static string FormSend {
            get {
                return ResourceManager.GetString("FormSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM..
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to програмістів..
        /// </summary>
        internal static string Programmers {
            get {
                return ResourceManager.GetString("Programmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тестувальників..
        /// </summary>
        internal static string Testers {
            get {
                return ResourceManager.GetString("Testers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна сторінка.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в Україні.
        /// </summary>
        internal static string TitleEnd {
            get {
                return ResourceManager.GetString("TitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to роботи.
        /// </summary>
        internal static string TitleMiddle {
            get {
                return ResourceManager.GetString("TitleMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт для пошуку.
        /// </summary>
        internal static string TitleStart {
            get {
                return ResourceManager.GetString("TitleStart", resourceCulture);
            }
        }
    }
}
