//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionVacancyViewModel_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionVacancyViewModel_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.Forms.ActionVacancyViewModel.uk", typeof(ActionVacancyViewModel_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateRegion поле має бути заповненим.
        /// </summary>
        internal static string CandidateRegion_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("CandidateRegion поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishLevel поле має бути заповненим.
        /// </summary>
        internal static string EnglishLevel_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("EnglishLevel поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience поле має бути заповненим.
        /// </summary>
        internal static string Experience_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("Experience поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromSalary поле має бути заповненим.
        /// </summary>
        internal static string FromSalary_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("FromSalary поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HowToWork поле має бути заповненим.
        /// </summary>
        internal static string HowToWork_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("HowToWork поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWords поле має бути заповненим (бажано &gt; 100 символів).
        /// </summary>
        internal static string KeyWords_поле_має_бути_заповненим__бажано___100_символів_ {
            get {
                return ResourceManager.GetString("KeyWords поле має бути заповненим (бажано > 100 символів)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongDescription поле має бути заповненим.
        /// </summary>
        internal static string LongDescription_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("LongDescription поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate поле має бути заповненим.
        /// </summary>
        internal static string Relocate_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("Relocate поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescription поле має бути заповненим.
        /// </summary>
        internal static string ShortDescription_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ShortDescription поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToSalary поле має бути заповненим.
        /// </summary>
        internal static string ToSalary_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ToSalary поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypesOfCompany поле має бути заповненим.
        /// </summary>
        internal static string TypesOfCompany_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("TypesOfCompany поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancyDomain поле має бути заповненим.
        /// </summary>
        internal static string VacancyDomain_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("VacancyDomain поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancyTitle поле має бути заповненим.
        /// </summary>
        internal static string VacancyTitle_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("VacancyTitle поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkCategory поле має бути заповненим.
        /// </summary>
        internal static string WorkCategory_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("WorkCategory поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальний опис.
        /// </summary>
        internal static string Детальний_опис {
            get {
                return ResourceManager.GetString("Детальний опис", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина детального опису має бути в діапазоні від 200 до 5000 символів.
        /// </summary>
        internal static string Довжина_детального_опису_має_бути_в_діапазоні_від_200_до_5000_символів {
            get {
                return ResourceManager.GetString("Довжина детального опису має бути в діапазоні від 200 до 5000 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина ключових слів має бути в діапазоні від 10 до 300 символів.
        /// </summary>
        internal static string Довжина_ключових_слів_має_бути_в_діапазоні_від_10_до_300_символів {
            get {
                return ResourceManager.GetString("Довжина ключових слів має бути в діапазоні від 10 до 300 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина короткого опису має бути в діапазоні від 30 до 250 символів.
        /// </summary>
        internal static string Довжина_короткого_опису_має_бути_в_діапазоні_від_30_до_250_символів {
            get {
                return ResourceManager.GetString("Довжина короткого опису має бути в діапазоні від 30 до 250 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина назви має бути в діапазоні від 10 до 100 символів.
        /// </summary>
        internal static string Довжина_назви_має_бути_в_діапазоні_від_10_до_100_символів {
            get {
                return ResourceManager.GetString("Довжина назви має бути в діапазоні від 10 до 100 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домен вакансії.
        /// </summary>
        internal static string Домен_вакансії {
            get {
                return ResourceManager.GetString("Домен вакансії", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досвід повинен сягати від 0 до 15 років.
        /// </summary>
        internal static string Досвід_повинен_сягати_від_0_до_15_років {
            get {
                return ResourceManager.GetString("Досвід повинен сягати від 0 до 15 років", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досвід роботи.
        /// </summary>
        internal static string Досвід_роботи {
            get {
                return ResourceManager.GetString("Досвід роботи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата від.
        /// </summary>
        internal static string Зарплата_від {
            get {
                return ResourceManager.GetString("Зарплата від", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата до.
        /// </summary>
        internal static string Зарплата_до {
            get {
                return ResourceManager.GetString("Зарплата до", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        internal static string Категорія {
            get {
                return ResourceManager.GetString("Категорія", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключові слова для пошуку.
        /// </summary>
        internal static string Ключові_слова_для_пошуку {
            get {
                return ResourceManager.GetString("Ключові слова для пошуку", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткий опис.
        /// </summary>
        internal static string Короткий_опис {
            get {
                return ResourceManager.GetString("Короткий опис", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінімальна зарплата не може перевищувати максимальну.
        /// </summary>
        internal static string Мінімальна_зарплата_не_може_перевищувати_максимальну {
            get {
                return ResourceManager.GetString("Мінімальна зарплата не може перевищувати максимальну", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регіон кандидата.
        /// </summary>
        internal static string Регіон_кандидата {
            get {
                return ResourceManager.GetString("Регіон кандидата", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Релокейт.
        /// </summary>
        internal static string Релокейт {
            get {
                return ResourceManager.GetString("Релокейт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ремоут / офіс.
        /// </summary>
        internal static string Ремоут___офіс {
            get {
                return ResourceManager.GetString("Ремоут / офіс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень англійської.
        /// </summary>
        internal static string Рівень_англійської {
            get {
                return ResourceManager.GetString("Рівень англійської", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип компанії.
        /// </summary>
        internal static string Тип_компанії {
            get {
                return ResourceManager.GetString("Тип компанії", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хто вам потрібен.
        /// </summary>
        internal static string Хто_вам_потрібен {
            get {
                return ResourceManager.GetString("Хто вам потрібен", resourceCulture);
            }
        }
    }
}
