//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangePasswordViewModel_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangePasswordViewModel_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.Forms.ChangePasswordViewModel.en", typeof(ChangePasswordViewModel_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmNewPassword field is required.
        /// </summary>
        internal static string ConfirmNewPassword_поле_є_обов_язковим {
            get {
                return ResourceManager.GetString("ConfirmNewPassword поле є обов\'язковим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email поле field is required.
        /// </summary>
        internal static string Email_поле_є_обов_язковим {
            get {
                return ResourceManager.GetString("Email поле є обов\'язковим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword field is required.
        /// </summary>
        internal static string NewPassword_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("NewPassword поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword field is required.
        /// </summary>
        internal static string OldPassword_поле_є_обов_язвовим {
            get {
                return ResourceManager.GetString("OldPassword поле є обов\'язвовим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum password length is 6 characters.
        /// </summary>
        internal static string Мінімальна_довжина_пароля___6_символів {
            get {
                return ResourceManager.GetString("Мінімальна довжина пароля - 6 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string Паролі_не_співпадають {
            get {
                return ResourceManager.GetString("Паролі не співпадають", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number, one uppercase letter, and one lowercase letter.
        /// </summary>
        internal static string Пароль_має_містити_принаймні_одну_цифру__одну_велику_літеру_та_одну_маленьку_літеру {
            get {
                return ResourceManager.GetString("Пароль має містити принаймні одну цифру, одну велику літеру та одну маленьку літе" +
                        "ру", resourceCulture);
            }
        }
    }
}
