//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefreshEmployerInfoViewModel_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefreshEmployerInfoViewModel_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.Forms.RefreshEmployerInfoViewModel.uk", typeof(RefreshEmployerInfoViewModel_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutCompany поле має бути заповненим.
        /// </summary>
        internal static string AboutCompany_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("AboutCompany поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName поле має бути заповненим.
        /// </summary>
        internal static string CompanyName_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("CompanyName поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyPosition поле має бути заповненим.
        /// </summary>
        internal static string CompanyPosition_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("CompanyPosition поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOY посилання.
        /// </summary>
        internal static string DOY_посилання {
            get {
                return ResourceManager.GetString("DOY посилання", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва компанії.
        /// </summary>
        internal static string Назва_компанії {
            get {
                return ResourceManager.GetString("Назва компанії", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиція в компанії.
        /// </summary>
        internal static string Позиція_в_компанії {
            get {
                return ResourceManager.GetString("Позиція в компанії", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про компанію.
        /// </summary>
        internal static string Про_компанію {
            get {
                return ResourceManager.GetString("Про компанію", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт компанії.
        /// </summary>
        internal static string Сайт_компанії {
            get {
                return ResourceManager.GetString("Сайт компанії", resourceCulture);
            }
        }
    }
}
