//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefreshCandidateInfoViewModel_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefreshCandidateInfoViewModel_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.Forms.RefreshCandidateInfoViewModel.uk", typeof(RefreshCandidateInfoViewModel_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyPosition поле має бути заповненим.
        /// </summary>
        internal static string CompanyPosition_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("CompanyPosition поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedSalary поле має бути заповненим.
        /// </summary>
        internal static string ExpectedSalary_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExpectedSalary поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExperienceWorkDescription поле має бути заповненим.
        /// </summary>
        internal static string ExperienceWorkDescription_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExperienceWorkDescription поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExperienceWorkTime поле має бути заповненим.
        /// </summary>
        internal static string ExperienceWorkTime_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExperienceWorkTime поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWords поле має бути заповненим.
        /// </summary>
        internal static string KeyWords_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("KeyWords поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkCategory поле має бути заповненим.
        /// </summary>
        internal static string WorkCategory_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("WorkCategory поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бажана мова спілкування.
        /// </summary>
        internal static string Бажана_мова_спілкування {
            get {
                return ResourceManager.GetString("Бажана мова спілкування", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варіанти зайнятості.
        /// </summary>
        internal static string Варіанти_зайнятості {
            get {
                return ResourceManager.GetString("Варіанти зайнятості", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина ключових слів має бути в діапазоні від 10 до 300 символів.
        /// </summary>
        internal static string Довжина_ключових_слів_має_бути_в_діапазоні_від_10_до_300_символів {
            get {
                return ResourceManager.GetString("Довжина ключових слів має бути в діапазоні від 10 до 300 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина опису має сягати від 50 до 500 символів.
        /// </summary>
        internal static string Довжина_опису_має_сягати_від_50_до_500_символів {
            get {
                return ResourceManager.GetString("Довжина опису має сягати від 50 до 500 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досвід роботи.
        /// </summary>
        internal static string Досвід_роботи {
            get {
                return ResourceManager.GetString("Досвід роботи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплатні очікування.
        /// </summary>
        internal static string Зарплатні_очікування {
            get {
                return ResourceManager.GetString("Зарплатні очікування", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        internal static string Категорія {
            get {
                return ResourceManager.GetString("Категорія", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключові слова.
        /// </summary>
        internal static string Ключові_слова {
            get {
                return ResourceManager.GetString("Ключові слова", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        internal static string Країна {
            get {
                return ResourceManager.GetString("Країна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string Місто {
            get {
                return ResourceManager.GetString("Місто", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис досвіду роботи.
        /// </summary>
        internal static string Опис_досвіду_роботи {
            get {
                return ResourceManager.GetString("Опис досвіду роботи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погодинна ставка.
        /// </summary>
        internal static string Погодинна_ставка {
            get {
                return ResourceManager.GetString("Погодинна ставка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада.
        /// </summary>
        internal static string Посада {
            get {
                return ResourceManager.GetString("Посада", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень англійської.
        /// </summary>
        internal static string Рівень_англійської {
            get {
                return ResourceManager.GetString("Рівень англійської", resourceCulture);
            }
        }
    }
}
