//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkForYou.WebUI.Resources.ViewModels.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefreshCandidateInfoViewModel_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefreshCandidateInfoViewModel_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkForYou.WebUI.Resources.ViewModels.Forms.RefreshCandidateInfoViewModel.en", typeof(RefreshCandidateInfoViewModel_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyPosition field is required.
        /// </summary>
        internal static string CompanyPosition_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("CompanyPosition поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedSalary field is required.
        /// </summary>
        internal static string ExpectedSalary_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExpectedSalary поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExperienceWorkDescription field is required.
        /// </summary>
        internal static string ExperienceWorkDescription_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExperienceWorkDescription поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExperienceWorkTime field is required.
        /// </summary>
        internal static string ExperienceWorkTime_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("ExperienceWorkTime поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWords field is required.
        /// </summary>
        internal static string KeyWords_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("KeyWords поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkCategory field is required.
        /// </summary>
        internal static string WorkCategory_поле_має_бути_заповненим {
            get {
                return ResourceManager.GetString("WorkCategory поле має бути заповненим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred language of communication.
        /// </summary>
        internal static string Бажана_мова_спілкування {
            get {
                return ResourceManager.GetString("Бажана мова спілкування", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment options.
        /// </summary>
        internal static string Варіанти_зайнятості {
            get {
                return ResourceManager.GetString("Варіанти зайнятості", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords must be between 10 and 300 characters long.
        /// </summary>
        internal static string Довжина_ключових_слів_має_бути_в_діапазоні_від_10_до_300_символів {
            get {
                return ResourceManager.GetString("Довжина ключових слів має бути в діапазоні від 10 до 300 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description should be between 50 and 500 characters long.
        /// </summary>
        internal static string Довжина_опису_має_сягати_від_50_до_500_символів {
            get {
                return ResourceManager.GetString("Довжина опису має сягати від 50 до 500 символів", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Досвід_роботи {
            get {
                return ResourceManager.GetString("Досвід роботи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary expectations.
        /// </summary>
        internal static string Зарплатні_очікування {
            get {
                return ResourceManager.GetString("Зарплатні очікування", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Категорія {
            get {
                return ResourceManager.GetString("Категорія", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Ключові_слова {
            get {
                return ResourceManager.GetString("Ключові слова", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Країна {
            get {
                return ResourceManager.GetString("Країна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Місто {
            get {
                return ResourceManager.GetString("Місто", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of work experience.
        /// </summary>
        internal static string Опис_досвіду_роботи {
            get {
                return ResourceManager.GetString("Опис досвіду роботи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        internal static string Погодинна_ставка {
            get {
                return ResourceManager.GetString("Погодинна ставка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company position.
        /// </summary>
        internal static string Посада {
            get {
                return ResourceManager.GetString("Посада", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English level.
        /// </summary>
        internal static string Рівень_англійської {
            get {
                return ResourceManager.GetString("Рівень англійської", resourceCulture);
            }
        }
    }
}
